# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b6eb578f49177a29f347079738ab06d6401f843b1aad1634f0a234b449a9cd1df922897fb07134e9c25892ed37ed7ac8e76d47004486539b08a4d4d10d1249d

test:
  secret_key_base: 243fea3dd92a42778f4abc88f1f842b2e4e64a6d86ba2df8293504f8f083fff3df940a38b2c212efbc36b53441e7ab1bf9a355ed4ad8cff282d582629e213144

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
