# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiyatTahmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metreKare', models.IntegerField(default=0)),
                ('odaSayisi', models.IntegerField(default=0)),
                ('fiyat', models.IntegerField(default=0)),
            ],
        ),
    ]
